### PR TITLE
tests: test Node.js 8 and 10

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by refinedblessing** [comment]
Hi @DanielRuf,

Thanks for your contribution, please can you add a description to this PR.

**Comment by DanielRuf** [comment]
No, because Node.js 9 and all other odd version numbers are short living Node.js branches between LTS and stable release branch.

**Comment by DanielRuf** [comment]
See the graph and where the Node.js 9 bar ends: https://github.com/nodejs/Release/blob/master/README.md

**Comment by DanielRuf** [comment]
It already reached its EOL and there are just 8 and 10 as downloads on the official website.

Before thid it was 6 and 8.

7, 9 and so on are early release branches for testing breaking changes before the APIs are stabilized / frozen.

**Comment by DanielRuf** [comment]
It already reached its EOL and there are just 8 and 10 as downloads on the official website.

Before this it was 6 and 8.

7, 9 and so on are early release branches for testing breaking changes before the APIs are stabilized / frozen.

**Comment by DanielRuf** [comment]
> In a few months, Node 9.x will reach its end-of-life. Odd-numbered releases never enter LTS. If you are currently using Node 9.x, consider moving to Node 8.x for increased stability, or Node 10.x if you're looking for the latest and greatest.

https://www.joyent.com/blog/nodejs-10-release-summary

**Pull request merged**
